include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/generated/**/*.dart
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false