name: welcome
description: Get started with dahliaOS
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  url_launcher: ^6.1.3

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/social_media/
    - assets/logos/dahliaOS/
